import { type Cinematica } from './cinematica-guion';

/**
 * Los guiones de los doce capítulos y el final. Una línea declara quién habla, qué dice y qué beat
 * visual enciende; el reloj lo calcula `relojDe`. Las reglas (ocho palabras por línea, sin raya,
 * beats declarados) las verifica `cinematica-guion.spec.ts` sobre este mismo arreglo.
 *
 * El arco: la tripulación deja atrás, capítulo a capítulo, sus reflejos de RxJS y Zone.js. En el 6
 * (el pico) llega la primera transmisión de la exploradora desde afuera; en el 11 contestan la
 * pregunta del viaje; el final se abre entero o a medias según lo que quedó establecido.
 */
export const CINEMATICAS: readonly Cinematica[] = [
  {
    capitulo: 0,
    titulo: 'Cómo la pantalla sabe qué cambió',
    ley: 'La pantalla no adivina: alguien tiene que avisarle.',
    apertura: ['titulo', 'naves'],
    beats: ['panel-viejo', 'arbol-entero', 'arbol-apagado', 'pregunta'],
    lineas: [
      { id: 'c0-circulos', quien: 'naveA', txt: 'Dos círculos. Eso era el caos.' },
      { id: 'c0-pantalla', quien: 'cap', txt: 'Bien. Ahora, nuestra pantalla.' },
      {
        id: 'c0-vieja',
        quien: 'naveB',
        txt: 'Sigue marcando la velocidad vieja.',
        beat: 'panel-viejo',
      },
      {
        id: 'c0-zone',
        quien: 'naveA',
        txt: 'En casa, Zone.js revisaba\ntodo el árbol.',
        beat: 'arbol-entero',
      },
      { id: 'c0-nadie', quien: 'naveB', txt: 'Acá nadie revisa nada.', beat: 'arbol-apagado' },
      {
        id: 'c0-pregunta',
        quien: 'cap',
        txt: '¿Y quién le avisó a la pantalla?',
        beat: 'pregunta',
      },
      {
        id: 'c0-avisa',
        quien: 'mascota',
        txt: 'Nadie revisa todo. Alguien avisa.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c0-guarden',
        quien: 'mascota',
        txt: 'Guarden esa pregunta.\nLos acompaña todo el viaje.',
      },
    ],
  },
  {
    capitulo: 1,
    titulo: 'El que avisa',
    ley: 'Un valor avisa solo a quien lo lee.',
    apertura: ['titulo', 'naves', 'caja-ambar'],
    beats: ['caja-ambar', 'hilo-lectura', 'aviso-pulso'],
    lineas: [
      { id: 'c1-caja', quien: 'naveB', txt: 'Encontré una caja.\nAdentro hay un número.' },
      {
        id: 'c1-cambio',
        quien: 'naveA',
        txt: 'Lo cambié… y mi panel se enteró.',
        beat: 'hilo-lectura',
      },
      { id: 'c1-cero', quien: 'cap', txt: 'El mío no. Sigue en cero.' },
      { id: 'c1-ella', quien: 'naveB', txt: '¿A ella le avisó y a vos no?' },
      {
        id: 'c1-grita',
        quien: 'mascota',
        txt: 'La caja no grita al espacio.',
        beat: 'mascota',
        hueco: 400,
      },
      { id: 'c1-leyo', quien: 'mascota', txt: 'Avisa a quien la leyó.', beat: 'aviso-pulso' },
      { id: 'c1-como-leer', quien: 'cap', txt: 'Nunca la leí.\n¿Cómo se lee una caja?' },
    ],
  },
  {
    capitulo: 2,
    titulo: 'El que se entera por otro',
    ley: 'Un derivado no se toca: sigue a su fuente.',
    apertura: ['titulo', 'naves'],
    beats: ['suma-a-mano', 'molecula-punteada', 'hilos-fuente', 'reposo'],
    lineas: [
      {
        id: 'c2-a-mano',
        quien: 'cap',
        txt: 'Rumbo es velocidad más viento.\nSúmenlo a mano.',
        beat: 'suma-a-mano',
      },
      { id: 'c2-vieja', quien: 'naveA', txt: 'Cambió el viento.\nTu suma quedó vieja.' },
      {
        id: 'c2-punteada',
        quien: 'naveB',
        txt: 'Esta molécula punteada\nya tiene la suma.',
        beat: 'molecula-punteada',
      },
      { id: 'c2-quien', quien: 'cap', txt: '¿Quién la escribió? Nadie la tocó.' },
      {
        id: 'c2-por-otro',
        quien: 'mascota',
        txt: 'Nadie la toca. Se entera por otro.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c2-rehace',
        quien: 'naveA',
        txt: '¿Se rehace con cada cambio del viento?',
        beat: 'hilos-fuente',
      },
      {
        id: 'c2-nadie-lee',
        quien: 'mascota',
        txt: 'Fíjense qué pasa si nadie la lee.',
        beat: 'reposo',
      },
    ],
  },
  {
    capitulo: 3,
    titulo: 'El que sale a hacer algo',
    ley: 'El que actúa repite cuando cambia lo que leyó.',
    apertura: ['titulo', 'naves', 'baliza-coral'],
    beats: ['baliza-coral', 'hilo-lectura', 'baliza-doble', 'rastro'],
    lineas: [
      { id: 'c3-baliza', quien: 'naveB', txt: 'Puse una baliza:\nsuena cuando cambia la caja.' },
      { id: 'c3-sono', quien: 'naveA', txt: 'Cambié la caja. Sonó sola.', beat: 'hilo-lectura' },
      { id: 'c3-viento', quien: 'cap', txt: 'Cambié el viento. No sonó.' },
      {
        id: 'c3-leyo',
        quien: 'mascota',
        txt: 'Solo vuelve por lo que leyó.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c3-dos',
        quien: 'naveB',
        txt: 'Y ahora suenan dos.\nLa vieja no paró.',
        beat: 'baliza-doble',
        hueco: 500,
      },
      { id: 'c3-rastro', quien: 'naveA', txt: 'Salir a hacer algo deja rastro.', beat: 'rastro' },
      { id: 'c3-apagar', quien: 'cap', txt: '¿Cómo se apaga la anterior\nantes de repetir?' },
    ],
  },
  {
    capitulo: 4,
    titulo: '¿Cambió, o solo se parece?',
    ley: 'Antes de avisar, el valor compara: ¿cambió de verdad?',
    apertura: ['titulo', 'naves'],
    beats: ['siete-dos-veces', 'coordenadas-gemelas', 'balanza', 'criterio'],
    lineas: [
      {
        id: 'c4-siete',
        quien: 'naveA',
        txt: 'Escribí siete. Y siete otra vez.',
        beat: 'siete-dos-veces',
      },
      { id: 'c4-nadie', quien: 'naveB', txt: 'La segunda vez nadie se enteró.' },
      {
        id: 'c4-igual',
        quien: 'mascota',
        txt: 'Si no cambió, no hay aviso.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c4-coordenadas',
        quien: 'cap',
        txt: 'Copié las coordenadas, idénticas.\nY todos se enteraron.',
        beat: 'coordenadas-gemelas',
        hueco: 500,
      },
      { id: 'c4-quien', quien: 'naveA', txt: '¿Idénticas para quién?', beat: 'balanza' },
      { id: 'c4-compara', quien: 'mascota', txt: 'El mundo compara antes de avisar.' },
      {
        id: 'c4-criterio',
        quien: 'mascota',
        txt: 'Y el criterio se puede elegir.',
        beat: 'criterio',
      },
      { id: 'c4-cual', quien: 'cap', txt: '¿Con qué criterio comparó mis coordenadas?' },
    ],
  },
  {
    capitulo: 5,
    titulo: 'Cuando el observador interviene',
    ley: 'Podés pisar un derivado; su fuente lo reinicia.',
    apertura: ['titulo', 'naves', 'mapa-rutas'],
    beats: ['mapa-rutas', 'mano-pisa', 'sector-nuevo', 'marcador-suspenso'],
    lineas: [
      { id: 'c5-primera', quien: 'naveA', txt: 'El mapa propone la primera ruta.' },
      {
        id: 'c5-tercera',
        quien: 'naveB',
        txt: 'Yo prefiero la tercera.\nLa marco a mano.',
        beat: 'mano-pisa',
      },
      { id: 'c5-no-tocaba', quien: 'cap', txt: 'Lo derivado no se tocaba.' },
      {
        id: 'c5-pisar',
        quien: 'mascota',
        txt: 'Este sí se deja pisar.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c5-sector',
        quien: 'naveA',
        txt: 'Cambió el sector.\nEl mapa trae rutas nuevas.',
        beat: 'sector-nuevo',
        hueco: 500,
      },
      {
        id: 'c5-mi-tercera',
        quien: 'naveB',
        txt: '¿Y mi tercera? No está en la lista.',
        beat: 'marcador-suspenso',
      },
      { id: 'c5-huerfana', quien: 'cap', txt: '¿Queda huérfana o vuelve a la fuente?' },
    ],
  },
  {
    capitulo: 6,
    titulo: 'El dato que todavía viaja',
    ley: 'Un dato que viaja tiene estado: cargando, error, valor.',
    apertura: ['titulo', 'naves', 'estado-en-viaje'],
    beats: ['estado-en-viaje', 'onda-debil', 'dos-paquetes', 'cruce'],
    lineas: [
      {
        id: 'c6-banda',
        quien: 'naveA',
        txt: '¿Escucharon? Hay algo en la banda vieja.',
        beat: 'transmision',
      },
      {
        id: 'c6-reciben',
        quien: 'nave4',
        txt: '…cap… ¿me… reciben?…',
        beat: 'onda-debil',
        hueco: 600,
      },
      { id: 'c6-exploradora', quien: 'naveB', txt: '¡Es la exploradora! Sigue afuera.' },
      { id: 'c6-donde', quien: 'cap', txt: '¡Exploradora! ¿Dónde estás?' },
      {
        id: 'c6-de-nuevo',
        quien: 'cap',
        txt: 'No contesta. Preguntá de nuevo,\nmás fuerte.',
        hueco: 900,
      },
      {
        id: 'c6-llega',
        quien: 'naveB',
        txt: 'Llega \x27sector ocho\x27…\ny ahora \x27sector siete\x27.',
        beat: 'dos-paquetes',
      },
      {
        id: 'c6-cual-vieja',
        quien: 'cap',
        txt: '¿Cuál es la vieja?\nDos preguntas, dos respuestas.',
        beat: 'cruce',
      },
      {
        id: 'c6-no-valor',
        quien: 'mascota',
        txt: 'Lo que viaja todavía no es un valor.',
        beat: 'mascota',
        hueco: 400,
      },
      { id: 'c6-estado', quien: 'mascota', txt: 'Pregunten en qué estado está.' },
      { id: 'c6-cancela', quien: 'cap', txt: 'Si pregunto de nuevo,\n¿la anterior se cancela?' },
    ],
  },
  {
    capitulo: 7,
    titulo: 'Los bordes del aparato',
    ley: 'Un aparato recibe por un borde, avisa por otro.',
    apertura: ['titulo', 'naves'],
    beats: ['repetidor', 'frecuencia-vieja', 'borde-salida', 'vacio'],
    lineas: [
      { id: 'c7-repetidor', quien: 'cap', txt: 'Armemos un repetidor\npara la exploradora.' },
      {
        id: 'c7-frecuencia',
        quien: 'naveA',
        txt: 'Necesita la frecuencia. Se la paso.',
        beat: 'repetidor',
      },
      {
        id: 'c7-vieja',
        quien: 'naveB',
        txt: 'Cambié la frecuencia\ny sigue en la vieja.',
        beat: 'frecuencia-vieja',
        hueco: 500,
      },
      {
        id: 'c7-vivo',
        quien: 'mascota',
        txt: 'Lo que entra sigue vivo adentro.',
        beat: 'mascota',
        hueco: 400,
      },
      { id: 'c7-avisa', quien: 'naveA', txt: '¿Y cuando encuentre algo,\ncómo nos avisa?' },
      {
        id: 'c7-borde',
        quien: 'mascota',
        txt: 'Por otro borde, hacia afuera.',
        beat: 'borde-salida',
      },
      { id: 'c7-sin', quien: 'cap', txt: 'Lo encendí sin frecuencia.', beat: 'vacio', hueco: 500 },
      { id: 'c7-exigir', quien: 'naveB', txt: 'Está escuchando la nada.\n¿Se puede exigir?' },
    ],
  },
  {
    capitulo: 8,
    titulo: 'Mirar la pantalla misma',
    ley: 'Pantalla y streams también se leen como valores.',
    apertura: ['titulo', 'naves'],
    beats: ['pipes-esclusa', 'puente', 'pantalla-vacia', 'pantalla-aparece'],
    lineas: [
      {
        id: 'c8-pipes',
        quien: 'naveB',
        txt: 'Tiro los pipes de RxJS.\nAcá no sirven.',
        beat: 'pipes-esclusa',
      },
      {
        id: 'c8-traducen',
        quien: 'mascota',
        txt: 'No los tiren. Se traducen.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c8-stream',
        quien: 'naveA',
        txt: '¿Un stream puede volverse\nun valor que avisa?',
        beat: 'puente',
      },
      { id: 'c8-reves', quien: 'mascota', txt: 'Y al revés. Nada de lo suyo sobra.' },
      {
        id: 'c8-pantalla',
        quien: 'cap',
        txt: 'Ahora el repetidor.\nQuiero mirar su pantalla.',
        hueco: 500,
      },
      {
        id: 'c8-no-estaba',
        quien: 'naveB',
        txt: 'La busqué apenas encendió. No estaba.',
        beat: 'pantalla-vacia',
      },
      {
        id: 'c8-valor',
        quien: 'mascota',
        txt: 'Miren la pantalla como un valor más.',
        beat: 'pantalla-aparece',
      },
      { id: 'c8-cuando', quien: 'naveA', txt: 'Ahora sí está.\n¿Desde cuándo se puede leer?' },
    ],
  },
  {
    capitulo: 9,
    titulo: 'Medir después de pintar',
    ley: 'Para medir la pantalla, esperá a que esté pintada.',
    apertura: ['titulo', 'naves', 'antena-boceto'],
    beats: ['antena-boceto', 'regla-cero', 'pintado', 'oidos-apilados'],
    lineas: [
      { id: 'c9-midan', quien: 'cap', txt: 'Midan la antena del repetidor. Exacta.' },
      {
        id: 'c9-cero',
        quien: 'naveA',
        txt: 'Mide cero. Pero la estoy viendo.',
        beat: 'regla-cero',
      },
      { id: 'c9-antes', quien: 'naveB', txt: '¿La mediste antes o después de pintarla?' },
      {
        id: 'c9-pinta',
        quien: 'mascota',
        txt: 'Este mundo primero pinta.\nDespués se mide.',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c9-oido',
        quien: 'naveA',
        txt: 'Le puse un oído a la antena.',
        beat: 'pintado',
        hueco: 500,
      },
      {
        id: 'c9-tres',
        quien: 'naveB',
        txt: 'Repintaron dos veces.\nAhora hay tres oídos.',
        beat: 'oidos-apilados',
      },
      { id: 'c9-rastro', quien: 'cap', txt: 'Otra vez el rastro. Como la baliza.' },
      { id: 'c9-cuando', quien: 'naveA', txt: '¿Y cuándo sé que ya pintó?' },
    ],
  },
  {
    capitulo: 10,
    titulo: 'Esperar a que se estabilice',
    ley: 'Ante una ráfaga de avisos, actuá cuando se calme.',
    apertura: ['titulo', 'naves'],
    beats: ['rafaga', 'eco-multiple', 'temperatura', 'calma'],
    lineas: [
      {
        id: 'c10-tormenta',
        quien: 'naveA',
        txt: '¡Tormenta en la banda! Es ella.',
        beat: 'transmision',
      },
      {
        id: 'c10-sector',
        quien: 'nave4',
        txt: '…sec… sector… sector oc…\n¡sector ocho!',
        beat: 'rafaga',
        hueco: 300,
      },
      {
        id: 'c10-pedacito',
        quien: 'naveB',
        txt: 'El repetidor contesta cada pedacito.',
        beat: 'eco-multiple',
      },
      { id: 'c10-cuatro', quien: 'cap', txt: 'Cuatro respuestas para un solo mensaje.' },
      {
        id: 'c10-fundir',
        quien: 'naveA',
        txt: 'Se va a fundir contestando a medias.',
        beat: 'temperatura',
      },
      {
        id: 'c10-no-termino',
        quien: 'mascota',
        txt: 'Ella todavía no terminó de hablar.',
        beat: 'mascota',
        hueco: 400,
      },
      { id: 'c10-calme', quien: 'mascota', txt: 'Esperen a que la banda se calme.', beat: 'calma' },
      {
        id: 'c10-cuanto',
        quien: 'cap',
        txt: '¿Cuánto? ¿Y si vuelve a hablar\nmientras esperamos?',
      },
    ],
  },
  {
    capitulo: 11,
    titulo: 'Quien lee, avisa',
    ley: 'Nadie revisa todo el árbol: quien lee, avisa.',
    apertura: ['titulo', 'naves', 'arbol-completo'],
    beats: ['arbol-completo', 'lectores-encendidos', 'zone-se-apaga', 'pregunta-brilla'],
    lineas: [
      { id: 'c11-repasemos', quien: 'cap', txt: 'Repasemos. Nadie revisó el árbol entero.' },
      { id: 'c11-igual', quien: 'naveA', txt: 'Y la pantalla se repintó igual.' },
      {
        id: 'c11-donde',
        quien: 'naveB',
        txt: 'Solo donde alguien leía algo que cambió.',
        beat: 'lectores-encendidos',
      },
      { id: 'c11-casa', quien: 'cap', txt: 'En casa, Zone.js lo revisaba\ntodo por nosotros.' },
      {
        id: 'c11-atras',
        quien: 'mascota',
        txt: 'Dejar atrás lo que conocen.\n¿Se acuerdan?',
        beat: 'mascota',
        hueco: 400,
      },
      {
        id: 'c11-quien',
        quien: 'naveB',
        txt: 'Entonces, ¿quién le avisó a la pantalla?',
        beat: 'pregunta-brilla',
        hueco: 500,
      },
      { id: 'c11-sabemos', quien: 'naveA', txt: 'Creo que ya lo sabemos.' },
      {
        id: 'c11-comprobar',
        quien: 'cap',
        txt: 'Sin Zone.js, entonces. Comprobémoslo.',
        beat: 'zone-se-apaga',
      },
    ],
  },
  {
    capitulo: 12,
    titulo: 'Quien lee, vuelve',
    ley: 'No se escapa de un mundo: se lo entiende.',
    apertura: ['titulo', 'naves', 'molecula-entera'],
    beats: ['molecula-entera', 'salida-iris', 'nave4-entra', 'regreso'],
    lineas: [
      {
        id: 'c12-banda',
        quien: 'naveA',
        txt: 'La banda está limpia.\nElla está cerca.',
        beat: 'transmision',
      },
      {
        id: 'c12-responden',
        quien: 'nave4',
        txt: '¡Al fin responden!\n¿Dónde se metieron?',
        hueco: 400,
      },
      { id: 'c12-reglas', quien: 'cap', txt: 'En un mundo que sigue reglas.' },
      {
        id: 'c12-salida',
        quien: 'naveB',
        txt: 'Todos los enlaces encendidos.\nSe abrió la salida.',
        beat: 'salida-iris',
        hueco: 500,
        si: 'completo',
      },
      {
        id: 'c12-lentos',
        quien: 'nave4',
        txt: 'Los veo. Salgan de una vez, lentos.',
        beat: 'nave4-entra',
        si: 'completo',
      },
      {
        id: 'c12-helado',
        quien: 'naveA',
        txt: 'Siempre tan aguafiestas.\nVamos por tu helado.',
        beat: 'regreso',
        si: 'completo',
      },
      {
        id: 'c12-punteados',
        quien: 'naveB',
        txt: 'Quedan enlaces punteados.\nLa salida está a medias.',
        beat: 'salida-iris',
        hueco: 500,
        si: 'incompleto',
      },
      {
        id: 'c12-medias',
        quien: 'nave4',
        txt: 'Los veo a medias. ¿Vienen o no?',
        beat: 'nave4-entra',
        si: 'incompleto',
      },
      {
        id: 'c12-casa',
        quien: 'cap',
        txt: 'Todavía no.\nEste mundo también es casa.',
        beat: 'regreso',
        si: 'incompleto',
      },
      {
        id: 'c12-suyas',
        quien: 'mascota',
        txt: 'Este mundo sigue reglas.\nAhora son suyas.',
        beat: 'mascota',
        hueco: 600,
      },
    ],
  },
];

export function cinematicaDe(capitulo: number): Cinematica | null {
  return CINEMATICAS.find((c) => c.capitulo === capitulo) ?? null;
}
